### ISSUE TITLE
Build Occurance Book

### ISSUE THREAD

**Issue by gidds** [Masters16/occurence_book#1]
Hi,

I noticed you made a python app for an occurance book. I am finding myself in the process of needing one as well. 
I downloaded your code and ran it in VSCode and found mispelled words and links. 

I made some fixes on my side and it is now displaying a header in the browser.
I am open to help build this application if you are interested.

**Comment by Masters16** [comment]
Hello there, sorry for the late reply but the project was not python codes maybe that is what is causing prpblems when you run it.On 20 Aug 2024, at 19:16, Gidds ***@***.***> wrote:﻿
Hi,
I noticed you made a python app for an occurance book. I am finding myself in the process of needing one as well.
I downloaded your code and ran it in VSCode and found mispelled words and links.
I made some fixes on my side and it is now displaying a header in the browser.
I am open to help build this application if you are interested.

**Comment by gidds** [comment]
Appologies for my misunderstanding and thank you for the reply.
